---
version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - ./config/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: always
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Bucharest
    hostname: PlexServer
    volumes:
      - ./config/plex:/config
      - ./tmp/plex:/transcode
      - ./media:/data
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./config/sonarr:/config
      - ./media:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: always
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "1000"
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    links:
      - influxdb
  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
  telegraf:
    container_name: telegraf
    image: telegraf:1.12.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc
#      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf